Reselling/Reselling.Presentation/Models/UserOrders.cs
using Reselling.Business.Models;
using System.Collections.Generic;
using System.Linq;

namespace Reselling.Presentation.Models
{
    public class UserOrders
    {
        public List<Order> OrderedTickets { get; set; }

        public UserOrders(User user, List<Order> orders)
        {
            OrderedTickets = orders.Where(item => item.Buyer.Id == user.Id).ToList();
        }
    }
}

Reselling/Reselling.Presentation/Models/UserTickets.cs
using System.Collections.Generic;
using System.Linq;
using Reselling.Business.Models;

namespace Reselling.Presentation.Models
{
    public class UserTickets
    {
        public List<Ticket> SellingTickets { get; set; }
        public List<Order> WaitingConfirmationTickets { get; set; }
        public List<Order> SoldTickets { get; set; }

        public UserTickets(User user, List<Ticket> tickets, List<Order> orders)
        {
            SellingTickets = tickets.Where(item => item.Seller.Id == user.Id && item.Status == "free").ToList();
            WaitingConfirmationTickets = orders.Where(order => order.Ticket.Seller.Id == user.Id && order.Status == "Waiting confirmation").ToList();
            SoldTickets = orders.Where(order => order.Ticket.Seller.Id == user.Id && order.Ticket.Status == "sold" && order.Status == "Confirmed").ToList();
        }
    }
}

Reselling/Reselling.Presentation/Controllers/ConfirmationController.cs
using Microsoft.AspNetCore.Mvc;
using Reselling.Data.Database;
using Reselling.Business.Models;
using Reselling.Presentation.Models.Confirmation;

namespace Reselling.Presentation.Controllers
{
    public class ConfirmationController : Controller
    {
        UnitOfWork _repo;

        public ConfirmationController(UnitOfWork repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Confirm(int id)
        {
            ConfirmModel model = new ConfirmModel() { OrderId = id };
            return View(model);
        }

        [HttpPost]
        public IActionResult Confirm(ConfirmModel model)
        {
            if (ModelState.IsValid)
            {
                Order order = _repo.Orders.GetById(model.OrderId);
                if (order != null)
                {
                    // Order confirmed
                    order.Status = "Confirmed";
                    order.TrackingNumber = model.TrackingNumber;
                    _repo.Orders.Update(order);
                    _repo.Save();

                    // Ticket sold
                    Ticket ticket = _repo.Tickets.GetById(order.Ticket.Id);
                    ticket.Status = "sold";
                    _repo.Tickets.Update(ticket);
                    _repo.Save();

                    return RedirectToAction("UserTickets", "User");
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Reject(int id)
        {
            RejectModel model = new RejectModel() { OrderId = id };
            return View(model);
        }

        [HttpPost]
        public IActionResult Reject(RejectModel model)
        {
            if (ModelState.IsValid)
            {
                Order order = _repo.Orders.GetById(model.OrderId);
                if (order != null)
                {
                    // Order rejected
                    order.Status = "Rejected";
                    order.Comment = model.Comment;
                    _repo.Orders.Update(order);
                    _repo.Save();

                    // Ticket free
                    Ticket ticket = _repo.Tickets.GetById(order.Ticket.Id);
                    ticket.Status = "free";
                    _repo.Tickets.Update(ticket);
                    _repo.Save();

                    return RedirectToAction("UserTickets", "User");
                }
            }
            return View(model);
        }
    }
}

Reselling/Reselling.Presentation/Controllers/UserController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Reselling.Presentation.Models;
using Microsoft.AspNetCore.Authorization;
using Reselling.Business.Models;
using Reselling.Data.Database;

namespace Reselling.Presentation.Controllers
{
    public class UserController : Controller
    {
        UnitOfWork _repo;

        public UserController(UnitOfWork repo)
        {
            _repo = repo;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult UserOrders()
        {
            User user = _repo.Users.GetAll().FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            UserOrders userOrders = new UserOrders(user, _repo.Orders.GetAll().ToList());
            return View(userOrders);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult UserTickets()
        {
            User user = _repo.Users.GetAll().FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            UserTickets userTickets = new UserTickets(user, _repo.Tickets.GetAll().ToList(), _repo.Orders.GetAll().ToList());
            return View(userTickets);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult UserInfo()
        {
            User user = _repo.Users.GetAll().FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name);
            return View(user);
        }

        public IActionResult UserList()
        {
            return View(_repo.Users.GetAll().ToList());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult ChangeRole(int id)
        {
            User user = _repo.Users.GetById(id);
            ChangeRoleModel userForChange = new ChangeRoleModel() { UserId = user.Id, Login = user.Login, RoleId = user.Role.Id };
            ViewBag.RolesList = _repo.Roles.GetAll().ToList();
            return View(userForChange);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult ChangeRole(ChangeRoleModel model)
        {
            if (ModelState.IsValid)
            {
                User user = _repo.Users.GetById(model.UserId);
                if (user != null)
                {
                    user.Role = _repo.Roles.GetById(model.RoleId);
                    _repo.Users.Update(user);
                    _repo.Save();

                    return RedirectToAction("UserList");
                }
                else
                {
                    ModelState.AddModelError("", @"Something happened ¯\_(ツ)_ /¯, try later..");
                }
            }
            ViewBag.RolesList = _repo.Roles.GetAll().ToList();
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult ChangeOwnData(int id)
        {
            User user = _repo.Users.GetById(id);
            return View(user);
        }

        [HttpPost]
        [Authorize]
        public IActionResult ChangeOwnData(User model)
        {
            if (ModelState.IsValid)
            {
                User user = _repo.Users.GetById(model.Id);
                if (user != null)
                {
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Address = model.Address;
                    user.Localization = model.Localization;
                    user.PhoneNumber = model.PhoneNumber;
                    _repo.Users.Update(user);
                    _repo.Save();
                    RouteData.Values["culture"] = model.Localization;
                    return RedirectToAction("UserInfo");
                }
                else
                {
                    ModelState.AddModelError("", @"Something happened ¯\_(ツ)_ /¯, try later..");
                }
            }
            return View(model);
        }

    }
}

Reselling/Reselling.Presentation/Views/User/ChangeOwnData.cshtml
﻿@model Reselling.Business.Models.User
@{
    ViewData["Title"] = Localizer["Change Data"];
}

<form asp-controller="User" asp-action="ChangeOwnData" method="post" class="form-horizontal">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label">@Localizer["FirstName"]</label>
        <div class="col-md-10">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label">@Localizer["LastName"]</label>
        <div class="col-md-10">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Address" class="col-md-2 control-label">@Localizer["Address"]</label>
        <div class="col-md-10">
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="col-md-2 control-label">@Localizer["Phone Number"]</label>
        <div class="col-md-10">
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Localization" class="col-md-2 control-label">@Localizer["Localization"]</label>
        <div class="col-md-10">
            <select class="form-control" id="select" asp-for="Localization">
                <option>en</option>
                <option>be</option>
                <option>ru</option>
            </select>
            <span asp-validation-for="Localization" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="reset" class="btn btn-default">@Localizer["Reset"]</button>
            <button type="submit" class="btn btn-primary">@Localizer["Change"]</button>
        </div>
    </div>
</form>

Reselling/Reselling.Presentation/Views/User/ChangeRole.cshtml
﻿@model Reselling.Presentation.Models.ChangeRoleModel
@{
    ViewData["Title"] = Localizer["Change Role"];
}

<form asp-controller="User" asp-action="ChangeRole" method="post" class="form-horizontal">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="UserId" value="@Model.UserId" name="UserId" />
    <div class="form-group">
        <label asp-for="RoleId" class="col-md-2 control-label">@Localizer["Role"]</label>
        <div class="col-md-10">
            <select class="form-control" id="select" asp-for="RoleId" asp-items="@(new SelectList(ViewBag.RolesList,"Id","Name"))">
            </select>
            <span asp-validation-for="RoleId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Login" class="col-md-2 control-label">@Localizer["User"]</label>
        <div class="col-md-10">
            <h5>
                @Model.Login
            </h5>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="reset" class="btn btn-default">@Localizer["Reset"]</button>
            <button type="submit" class="btn btn-primary">@Localizer["Change"]</button>
        </div>
    </div>
</form>

Reselling/Reselling.Presentation/Views/User/UserInfo.cshtml
@model Reselling.Business.Models.User

@{
    ViewData["Title"] = "UserInfo";
}

<br />
<div class="jumbotron">
    <h3>@Localizer["Information"]:</h3>
    <div class="clearfix">
        @*<img src="@item.Photo" alt="@item.photo" />*@
        <h5>
            @Localizer["Login"] : @Model.Login
        </h5>
        <h5>
            @Localizer["Password"] : @Model.Password
        </h5>
        <h5>
            @Localizer["Name"] : @Model.FirstName @Model.LastName
        </h5>
        <h5>
            @Localizer["Address"] : @Model.Address
        </h5>
        <h5>
            @Localizer["PhoneNumber"] : @Model.PhoneNumber
        </h5>
        <h5>
            @Localizer["Local"] : @Model.Localization
        </h5>
        <h5>
            @Localizer["Role"] : @Model.Role.Name
        </h5>
    </div>
    <p><a class="btn btn-primary btn-lg" asp-controller="User" asp-action="ChangeOwnData" asp-route-id="@Model.Id">@Localizer["Edit"]</a></p>
</div>

Reselling/Reselling.Presentation/Views/User/UserList.cshtml
﻿@model List<Reselling.Business.Models.User>
@{
    int counter = 1;
    ViewData["Title"] = Localizer["List of Users"];
}

<form asp-controller="User" asp-action="UserList" method="post" class="form-horizontal">
    <h2>@ViewData["Title"]</h2>
    <hr />
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>№</th>
                    <th>@Localizer["User"]</th>
                    <th>@Localizer["Name"]</th>
                    <th>@Localizer["Role"]</th>
                    <th>@Localizer["Action"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Reselling.Business.Models.User user in Model)
                {
                    <tr>
                        <td>@(counter++)</td>
                        <td>@user.Login</td>
                        <td>@user.FirstName @user.LastName</td>
                        <td>@user.Role.Name</td>
                        <td>
                            @if (User.Identity.Name != user.Login)
                            {
                                <a asp-controller="User" asp-action="ChangeRole" class="btn btn-primary btn-xs" asp-route-id="@user.Id">@Localizer["Change Role"]</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</form>

Reselling/Reselling.Presentation/Views/User/UserOrders.cshtml
@model Reselling.Presentation.Models.UserOrders

@{
    ViewData["Title"] = "UserOrders";
}
<br />
<div class="jumbotron">
    <h3>@Localizer["You orders"], @User.Claims.FirstOrDefault(claim => claim.Type == "UserName").Value:</h3>
    <hr />
    @if (Model.OrderedTickets.Count > 0)
    {
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th>@Localizer["Event"]</th>
                    <th>@Localizer["Event date"]</th>
                    <th>@Localizer["Price"]</th>
                    <th>@Localizer["Order status"]</th>
                    <th>@Localizer["Tracking number"]</th>
                    <th>@Localizer["Comment"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model.OrderedTickets)
                {
                    <tr class="active">
                        <td>@order.Ticket.Event.Name</td>
                        <td>@order.Ticket.Event.Date.ToString("dd.MM.yyyy")</td>
                        <td>@order.Ticket.Price</td>
                        <td>@order.Status</td>
                        <th>@order.TrackingNumber</th>
                        <th>@order.Comment</th>
                    </tr>
                }
            <tbody>
        </table>
    }
    else
    {
        <h3>@Localizer["Your order list is empty"]</h3>
    }
</div>
       
        

Reselling/Reselling.Presentation/Views/User/UserTickets.cshtml
@model Reselling.Presentation.Models.UserTickets

@{
    ViewData["Title"] = Localizer["UserTickets"];
}
<br />
<div class="jumbotron">
    <h3>@Localizer["You tickets"], @User.Claims.FirstOrDefault(claim => claim.Type == "UserName").Value:</h3>
    <hr />
    @if (Model.SellingTickets.Count == 0 && Model.SoldTickets.Count == 0 && Model.WaitingConfirmationTickets.Count == 0)
    {
        <h3>@Localizer["Your ticket list is empty"]</h3>
    }
    else
    {
        <ul class="nav nav-tabs">
            <li class="active"><a href="#selling" data-toggle="tab" aria-expanded="false">@Localizer["Selling tickets"]</a></li>
            <li class=""><a href="#waitingConfirmation" data-toggle="tab" aria-expanded="false">@Localizer["Waiting Confirmation tickets"]</a></li>
            <li class=""><a href="#sold" data-toggle="tab" aria-expanded="false">@Localizer["Sold tickets"]</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="selling">
                @if (Model.SellingTickets.Count > 0)
                {
                    <table class="table table-striped table-hover ">
                        <thead>
                            <tr>
                                <th>@Localizer["Event"]</th>
                                <th>@Localizer["Event date"]</th>
                                <th>@Localizer["Price"]</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var ticket in Model.SellingTickets)
                            {
                                <tr class="active">
                                    <td>@ticket.Event.Name</td>
                                    <td>@ticket.Event.Date.ToString("dd.MM.yyyy")</td>
                                    <td>@ticket.Price</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <h3>@Localizer["You do not sell tickets"]</h3>
                }
            </div>
            <div class="tab-pane fade" id="waitingConfirmation">
                @if (Model.WaitingConfirmationTickets.Count > 0)
                {
                    <table class="table table-striped table-hover ">
                        <thead>
                            <tr>
                                <th>@Localizer["Event"]</th>
                                <th>@Localizer["Event date"]</th>
                                <th>@Localizer["Price"]</th>
                                <th>@Localizer["Buyer"]</th>
                                <th>@Localizer["Action"]</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var order in Model.WaitingConfirmationTickets)
                            {
                                <tr class="active">
                                    <td>@order.Ticket.Event.Name</td>
                                    <td>@order.Ticket.Event.Date.ToString("dd.MM.yyyy")</td>
                                    <td>@order.Ticket.Price</td>
                                    <td>@order.Buyer.Login</td>
                                    <td>
                                        <a asp-controller="Confirmation" asp-action="Confirm" asp-route-id="@order.Id">@Localizer["Confirm"]</a>
                                        <a asp-controller="Confirmation" asp-action="Reject" asp-route-id="@order.Id">@Localizer["Reject"]</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <h3>@Localizer["You have no tickets to confirm"]</h3>
                }
            </div>
            <div class="tab-pane fade" id="sold">
                @if (Model.SoldTickets.Count > 0)
                {
                    <table class="table table-striped table-hover ">
                        <thead>
                            <tr>
                                <th>@Localizer["Event"]</th>
                                <th>@Localizer["Event date"]</th>
                                <th>@Localizer["Price"]</th>
                                <th>@Localizer["Buyer"]</th>
                                <th>@Localizer["Track Number"]</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var order in Model.SoldTickets)
                            {
                                <tr class="active">
                                    <td>@order.Ticket.Event.Name</td>
                                    <td>@order.Ticket.Event.Date.ToString("dd.MM.yyyy")</td>
                                    <td>@order.Ticket.Price</td>
                                    <td>@order.Buyer.Login</td>
                                    <td>@order.TrackingNumber</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <h3>@Localizer["You have no sold tickets"]</h3>
                }
            </div>
        </div>
    }
</div>